name: C/C++ CI

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  # - name: Install CMake
  #    run: sudo apt-get install cmake
  #  - name: Create Build Directory
  #    run: mkdir build
      
    - name: Configure Project
      run: cmake -S . -B build
      
    - name: Build Project
      run: cmake --build build

    - name: List builded files
      run: ls
      
    - name: Upload the Build
      uses: actions/upload-artifact@v4
      with:
       name: test_artifact
       path:  build/test
       compression-level: 9
       retention-days: 1
